dat<-read.delim("./db_final.tsv") 
summary(dat)
hist(dat$G)
str(dat)
boxplot(dat$G)
boxplot(dat$G ~ dat$TCal )
boxplot(dat$G ~ dat$TCal, xlab="Calcination Temp [C]", ylab="Resistance") 
library("vioplot") 
library("ggplot2")
mod<-lm(dat$G ~ dat$TCal)
plot(dat$G ~ dat$TCal)
