This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file ./article.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file article.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file article.acr....done (6 lines written, 0 warnings).
Output written in article.acr.
Transcript written in article.alg.
