This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file ./article.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file article.acn....done (58 entries accepted, 0 rejected).
Sorting entries....done (409 comparisons).
Generating output file article.acr....done (54 lines written, 0 warnings).
Output written in article.acr.
Transcript written in article.alg.
